
#
# Configuration file for Travis CI
# https://travis-ci.org/
#

---

language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.12
  - 2.13.3

jdk:
  - openjdk11
  - openjdk14
  - oraclejdk11
  - oraclejdk14

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false


