
#
# Configuration file for Travis CI
# https://travis-ci.org/
#

---

language: scala

os: linux

dist: bionic

scala:
  - 2.13.3

jdk:
  - openjdk11
  - openjdk14
  - openjdk15
  - oraclejdk11
  - oraclejdk14
  - oraclejdk15

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report


