
#
# Configuration file for Travis CI
# https://travis-ci.org/
#

language: scala

scala:
   - 2.12.7

jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
  - oraclejdk11

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false


