---
# CI configuration
# https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

name: Scala CI

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 11
        - 17
        scala:
        - 2.13.10
        - 3.3.0
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: adopt
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots --show-version install
    - name: Build with sbt
      run: sbt '++ ${{ matrix.scala }}' scalaVersion sbtVersion version clean compile test package assembly


