---
# CI configuration
# https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

name: Scala CI

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 11.0.21
        - 21.0.1
        scala:
        - 2.13.14
        - 3.4.2
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots --show-version install
    - name: Build with sbt
      run: sbt '++ ${{ matrix.scala }}' scalaVersion sbtVersion version clean compile test package assembly


